### 1 ere Question 
J'ai essayé de faire 3 exemples afin de donner les 3 différents réultats possibles


In [20]:
import math
import numpy as np
from sklearn import linear_model
from os import mkdir

def nextpower(n) :    
    if type(n) == int :
        return 2**n
    elif type(n) == float :
        return 2**(int(n+1))
    else :
         print("Erreur n n'est pas un nombre reel")
a = ['pipi']
print ('2^3 = ' , nextpower(3))
print('2^(3.5)=' , nextpower(3.5))
print('2^(a)=' , nextpower(a))


    
    

2^3 =  8
2^(3.5)= 16
Erreur n n'est pas un nombre reel
2^(a)= None


## 2 eme Question
Slicing

In [12]:
import math
import numpy as np
from sklearn import linear_model
from os import mkdir

alphabet = 'abcdefghijklmnopqrstuvwxyz'
##slice cfilorux ()
resp1 = alphabet[2:12:3]+alphabet[14:25:3]
print('la reponse 1 est : ', resp1)
##2 façons de slice 
resp2 = alphabet[21:26:2]
print('la reponse 2 est :  ', resp2)
resp2bis = alphabet[-5::2]
print('la reponse 2 bis est :  ', resp2bis)

la reponse 1 est :  cfilorux
la reponse 2 est :   vxz
la reponse 2 bis est :   vxz


## 3 eme Question
 Pi avec 9 decimales

In [19]:
import math
import numpy as np
from sklearn import linear_model
from os import mkdir
print(round(math.pi,9))

3.141592654


## 4 eme Question
nombre d'occurence de chaque lettre HelLo WorLd!!

In [7]:
import math
import numpy as np
from sklearn import linear_model
from os import mkdir


s='HelLo WorLd!!'

def OccurenceKeydict(k) :
    resultdict = dict()
    resultdict = {}  ## initialisation
    i=0
    while i < len(k) :
        if k[i] in resultdict : ## test si la clé est présente dans le dictionnaire
            resultdict[k[i]] += 1 ## clé existe on incremente
        else :
            resultdict[k[i]] = 1 ## ajout de la clé au dictionnaire
        i+=1
    print('le dictionnaire réponse est : ', resultdict)
OccurenceKeydict(s)

le dictionnaire réponse est :  {'H': 1, 'e': 1, 'l': 1, 'L': 2, 'o': 2, ' ': 1, 'W': 1, 'r': 1, 'd': 1, '!': 2}


## 5 eme question
Fonction de codage par inversin de lettre

In [8]:
import math
import random as r
import numpy as np
from sklearn import linear_model
from os import mkdir

def CodageInvLettre (s) :
    TableCodage = dict ()
    TableCodage = {}
    ResultList = []
    ResultString=''
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    x = list(range(26))
    r.shuffle(x) ##liste corespondance indice i->x(i)
    i = 0
    j = 0
    while i < len(alphabet) :
        TableCodage[alphabet[i]]=alphabet[x[i]] ##dictionnaire lettre avec sa corresponance
        i += 1
    print(TableCodage)
    while j < len(s) :
        ResultList.append(TableCodage[s[j]])
        j += 1
    ResultString = ''.join(ResultList) 
    return ResultString

print (CodageInvLettre ('marypoppins'))

{'a': 'c', 'b': 's', 'c': 'o', 'd': 'i', 'e': 'y', 'f': 'f', 'g': 'a', 'h': 'j', 'i': 'e', 'j': 'z', 'k': 'm', 'l': 'n', 'm': 'p', 'n': 't', 'o': 'v', 'p': 'u', 'q': 'w', 'r': 'r', 's': 'q', 't': 'b', 'u': 'h', 'v': 'k', 'w': 'x', 'x': 'g', 'y': 'd', 'z': 'l'}
pcrduvuuetq


## 6 eme question
2 

In [15]:
import time
import math
import random as r
import numpy as np
from sklearn import linear_model
from os import mkdir

## 1 ere Solution avec boucle 

DifTpsExec = 0

def CalculAvecBoucle (rang) :
    global DifTpsExec
    debut=time.time()
    result=2
    for i in range(1,rang) : ##Boucle for
        result = result * (4 * i**2)/((4 * i**2)-1)
    DifTpsExec = (time.time()) - debut
    print("Le temps d'execution avec boucle est : " , DifTpsExec)
    return result
    


## 2 emem Solution sans boucle

def CalculSansBoucle (rang) :
    global DifTpsExec
    debut = time.time()
    b = np.arange(1,rang)
    c = np.arange(1, (2 * rang +1 ), 2) ##suite des chiffres impair jusqu'à rang
    d = np.multiply(4 * b ,b) ## 4* i*i
    e = np.multiply(c[:(rang-1)],c[1:]) ##(2*i-1)*(2*i+1)
    f = np.multiply(d,1/e)
    result = 2 * np.prod(f) 
    tempsexec = (time.time()) - debut
    Rap = DifTpsExec/tempsexec
    DifTpsExec = DifTpsExec - tempsexec
    print("Le temps d'execution vectoriel est : " , tempsexec)
    print("l'execution vectoriel est: ",Rap, " fois plus rapide" )
    print("l'ecart est : ", DifTpsExec)
    return result

print(CalculAvecBoucle(100000))   
print(CalculSansBoucle(100000))




Le temps d'execution avec boucle est :  0.08954286575317383
3.1415847995787733
Le temps d'execution vectoriel est :  0.0028619766235351562
l'execution vectoriel est:  31.28707097634122  fois plus rapide
l'ecart est :  0.08668088912963867
3.14158479958


## 7 eme question 
 quicksort
 

In [21]:
import time
import math
import random as r
import numpy as np
from sklearn import linear_model
from os import mkdir

def quicksort(ll) :
    
    if len(ll) <= 1  :
        return ll
    else :
        pivot = ll.pop()
        P = [pivot]
        less = []
        greater = []
    for x in ll :
        if x <= pivot :
            less.append(x)
        else :
            greater.append(x)
    return quicksort(less)+P+quicksort(greater)
## exemple
ll = [-2, 3, 5, 1, 3]
print(quicksort(ll))


[-2, 1, 3, 3, 5]


## 8 eme question
Creation Matrice 5x6 
operation sur colonnes et ensuite masque valeur


In [45]:
import time
import math
import random as rand
import numpy as np
from sklearn import linear_model
from os import mkdir

## creation Matrix
a = np.random.uniform(-1,1,(5,6)) ##Matrice 5x6 avec coef aleatoires dans [-1,1]
print("la matrice est:\n", a)
a[::,::2] = a[::,::2] - 2 * a[::,1::2] ##opération sur les colonnes
print("la matrice après opération est:\n", a)
row_mask = a >= 0 
print("Le masque binaire est \n", row_mask)
print("Résultat final est : \n", a[row_mask])



la matrice est:
 [[-0.95547369  0.4122763   0.75385212  0.54158744  0.0847623  -0.47845536]
 [-0.10104452  0.3379693  -0.50904651 -0.94310688 -0.38894855 -0.99647391]
 [-0.74939479 -0.89345892  0.57353983  0.61900343  0.89722523 -0.59428678]
 [-0.83240609  0.75566462 -0.06757071 -0.13828724  0.86338934  0.57382138]
 [ 0.43151265  0.24355736 -0.27456931  0.82107563  0.24305556 -0.21422622]]
la matrice après opération est:
 [[-1.78002629  0.4122763  -0.32932277  0.54158744  1.04167302 -0.47845536]
 [-0.77698313  0.3379693   1.37716724 -0.94310688  1.60399927 -0.99647391]
 [ 1.03752306 -0.89345892 -0.66446704  0.61900343  2.08579879 -0.59428678]
 [-2.34373533  0.75566462  0.20900378 -0.13828724 -0.28425343  0.57382138]
 [-0.05560208  0.24355736 -1.91672057  0.82107563  0.67150799 -0.21422622]]
Le masque binaire est 
 [[False  True False  True  True False]
 [False  True  True False  True False]
 [ True False False  True  True False]
 [False  True  True False False  True]
 [False  True Fals

## 9 eme question


In [1]:
import time
import math
import random as rand
import numpy as np
from sklearn import linear_model
from os import mkdir

## creation Matrix
a = np.random.uniform(-1,1,(5,20)) ##Matrice 5x20 avec coef aleatoires dans [-1,1]
m = np.dot(a,np.transpose(a)) ##multiplication matricielle
print(np.allclose(m, np.transpose(m)))##transpose(M)==M <=> M symetrique
eighenvalues = np.linalg.eigh(m)[0]
print("les Valeurs Propres de M sont \n" ,  eighenvalues)## Valeurs propres de M
print("la matrice est bien semi definie positive car ses valeurs propres sont positives", eighenvalues > 0 )
print("la matrice est de rang", len(eighenvalues))


True
les Valeurs Propres de M sont 
 [  4.79870075   5.76691907   6.7293173    8.10100657  10.33093867]
la matrice est bien semi definie positive car ses valeurs propres sont positives [ True  True  True  True  True]
la matrice est de rang 5


## 2 eme Partie


In [1]:
from os import path
import pandas as pd
import urllib
import zipfile
import sys
import numpy as np

url ='https://archive.ics.uci.edu/ml/machine-learning-databases/00235/'
filename = 'household_power_consumption'
zipfilename = filename +'.zip'
Location = url + zipfilename
# testing existence of file
if sys.version_info >= (3,0):
    if not(path.isfile('zipfilename')):
        urllib.request.urlretrieve(Location, zipfilename)
    else:
        if not(path.isfile('zipfilename')):
            urllib.urlretrieve(Location, zipfilename)
#unzip part
zip = zipfile.ZipFile(zipfilename)
zip.extractall()
na_values = ['?', '']
fields = ['Date', 'Time', 'Global_active_power']
df = pd.read_csv(filename+'.txt', sep=';', nrows=200000, na_values = na_values, usecols=fields)


## 1 ere question

In [4]:
##detecter et denombrer le nombre de lignes ou valeurs manquantes
print(df.info())
df1 = df.isnull() ## masque binaire
df2 = df1[df1.Global_active_power == True] ## sous dataFrame avec les valeur nulles
nblignes = df2.Global_active_power.shape[0]
print ('le nombre de lignes avec une valeur manquante est: ', nblignes)
##supprimer toutes les lignes avec une valuer manquante

df.dropna(axis=0, how='any', thresh=None, subset=[df.Global_active_power], inplace=False)



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 3 columns):
Date                   200000 non-null object
Time                   200000 non-null object
Global_active_power    196268 non-null float64
dtypes: float64(1), object(2)
memory usage: 4.6+ MB
None
le nombre de lignes avec une valeur manquante est:  3732


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.


 ## 2 eme question 

NameError: name 'c' is not defined